/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.parcialModelo;

import java.util.Scanner;

public class Main {

    public static void main(String[] args) {

        Scanner sc = new Scanner(System.in);
        int M;
        int N;
        double[][] A;

        //pedimos los datos a ingresar
        // Primer valor
        System.out.println("Por favor ingrese el valor de las filas");
        M = sc.nextInt();
        while (M < 3) {
            System.out.println("Por favor ingrese un valor igual o superior a 3");
            M = sc.nextInt();
        }

        //Segundo valor
        System.out.println("Por favor ingrese el valor de las filas");
        N = sc.nextInt();
        while (N < 2) {
            System.out.println("Por favor ingrese un valor igual o superior a 2");
            N = sc.nextInt();
        }
        System.out.println("Los valores ingresados son " + M + " y " + N);
        A = new double[M][N];

        //Pedimos ingresar los datos del array
        System.out.println("Por favor, ingrese los valores de la matriz");
        for (int i = 0; i < A.length; i++) {
            for (int j = 0; j < A[0].length; j++) {
                System.out.println("Valor para la fila " + (i + 1) + " " + "columna " + (j + 1));
                A[i][j] = sc.nextInt();

            };
        };
        //mostrar por consola la matriz
        System.out.println("La matriz es: ");

        for (int i = 0; i < A.length; i++) {//filas
            for (int j = 0; j < A[0].length; j++) {//columnas
                System.out.print(A[i][j] + " ");
            }
            System.out.println();//salto de linea
        }

        //Generamos la nueva matriz
        double[][] arrayB = new double[M][1];

        for (int i = 0; i < arrayB.length; i++) {
            for (int j = 0; j < A[0].length; j++) {
                arrayB[i][0] += A[i][j];
            }

        }

        //Mostramos la nueva matriz
        System.out.println("La nueva matriz es: ");

        for (int i = 0; i < A.length; i++) {//filas
            //columnas
            System.out.print(arrayB[i][0] + " ");

            System.out.println();//salto de linea
        }
    //Generamos la matriz de tamano N filas y 2 columnas
    double [][] arrayC = new double[M][2];


      for (int i = 0; i < arrayC.length; i++) {
          for (int j = 0; j < 1; j++) {
              arrayC[i][j] = arrayB[i][j];
          }
      }


    //Ordenamos la primera fila
    
    int n = arrayC.length;

        boolean intercambiado;
        do {
            intercambiado = false;
            for (int i = 1; i < n; i++){
                if (arrayC[i-1][0] < arrayC[i][0] ) {
                    double aux = arrayC[i-1][0];
                    arrayC[i-1][0] = arrayC[i][0];
                    arrayC[i][0] = aux;
                    intercambiado = true;
                } 
            }
        } while (intercambiado);
    
    
    for (int i = 0; i < arrayC.length; i++) {
        for (int j = 0; j < arrayB.length; j++) {
            if(arrayC[i][0]==arrayB[j][0]){
                arrayC[i][1] = (j+1);
            }
        }
    }




     //mostrar por consola la tercera matriz
        System.out.println("La última matriz es: ");

        for (int i = 0; i < arrayC.length; i++) {//filas
            for (int j = 0; j < arrayC[0].length; j++) {//columnas
                System.out.print(arrayC[i][j] + " ");
            }
            System.out.println();//salto de linea
        }

        //Mostramos la suma de la primera columna de la matriz

        double resultado = 0.0;

        for(int i = 0; i < arrayC.length; i++){
            resultado += arrayC[i][0];

        };
        System.out.println("La suma de los elementos de la columna 1 de esta matriz es: "+ resultado);


    }



    

}
